### ISSUE TITLE
fix the pipeline and release process as we have PR numbers now as part of merge

### ISSUE THREAD

**Issue by mishraomp** [bcgov/nr-oracle-service#57]

**Comment by mishraomp** [comment]
@DerekRoberts getting some ideas here, to move some old sh.t out. and align it with our QSOS, the helm release GHA has a way to allow skip packaging which we can leverage to automate end to end.
`skip_packaging: This option, when populated, will skip the packaging step. This allows you to do more advanced packaging of your charts (for example, with the helm package command) before this action runs. This action will only handle the indexing and publishing steps.`
https://github.com/helm/chart-releaser-action?tab=readme-ov-file#inputs

**Comment by DerekRoberts** [comment]
@mishraomp So we could include a lot more, but hold back as appropriate? Promising!
